# Generated by Django 4.1 on 2023-08-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='body',
            new_name='publicacion',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='categoria',
            field=models.CharField(choices=[('Plataforma', 'Plataforma'), ('Curso', 'Curso'), ('Canal', 'Canal')], default='Sin categoría', max_length=30),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='fecha',
            field=models.DateField(default='2023-01-01', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='lenguaje',
            field=models.CharField(default='Sin categoría', max_length=250),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='portada',
            field=models.CharField(default='Sin portada', max_length=250),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='resumen',
            field=models.TextField(default='Sin resumen', max_length=250),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='titulo',
            field=models.CharField(default='Sin titulo', max_length=250),
        ),
    ]
